### ISSUE TITLE
Evaluate condition more safely

### ISSUE THREAD

**Issue by arogachev** [yiisoft/requirements#55]
From the experience, Symfony Expression Language component could be useful for this purpose.

https://github.com/symfony/expression-language

Right now it's just a simple `eval` and we all know how dangerous it could be.

https://github.com/yiisoft/requirements/blob/f967516c6b7c48a88e58c2516dbaf187abcde75c/src/RequirementsChecker.php#L377

**Comment by samdark** [comment]
True but in this case it's critical to avoid extra dependencies for this package.
