### ISSUE TITLE
Research public properties/methods in `RequirementsChecker` and hide unneeded

### ISSUE THREAD

**Issue by vjik** [yiisoft/requirements#76]
For example, `normalizeRequirement()` and `$result`.

**Comment by rossaddison** [comment]
Hi vjik, getting the following reminder when running 'php requirements.php' at the console: 

````
Deprecated: Creation of dynamic property Yiisoft\Requirements\RequirementsChecker::$result is deprecated in C:\wamp128\www\invoice\vendor\yiisoft\requirements\src\RequirementsChecker.php on line 67
````

Any ideas why this is hapenning?

**Comment by samdark** [comment]
Weird. There is a property defined: https://github.com/yiisoft/requirements/blob/master/src/RequirementsChecker.php#L64

**Comment by vjik** [comment]
> Any ideas why this is hapenning?

Seems, you use non-actual version of package. I fixed it here: https://github.com/yiisoft/requirements/pull/71

**Comment by vjik** [comment]
Issue from first message is actual.
